upstreamProjects:
  Mule-runtime/mule-policy-api/1.4.0-TESTCYCLE-2020-DRY-RUN
# Comment public setting to get oldMuleArtifact from private repo till we move them to the public Repo
# Uncomment it after they are copied
#mavenSettingsXmlId : mule-runtime-maven-settings-MuleSettings
projectType: runtime
enableMavenTestStage: false
